### ISSUE TITLE
Package for Bionic Beaver

### ISSUE THREAD

**Issue by xuanruiqi** [MatthewFluet/mlton-ppa#1]
Ubuntu 18.04 has been released lately but the package hasn't yet been released yet. I think the same package would work, it would just need to be released under Bionic. Thanks.

**Comment by MatthewFluet** [comment]
I've copied the Xenial packages over to Bionic (which is what I had done for Artful).  Let me know if they appear to be working.

**Comment by xuanruiqi** [comment]
Works pretty well. Thanks!
